import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillInstagram, AiFillLinkedin } from "react-icons/ai";

export default function Home() {
  return (
    <>
      <Head>
        <title>React Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between ">
            <h1 className="text-xl font-burtons ">kiran</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-4xl py-2 font-medium text-teal-600">
              Kiran Madiwalar
            </h2>
            <h3 className="text-xl py-2">Web developer</h3>

            <p className="text-md py-5 leading-8 text-gray-800">
              A passinated web developer seeking for an opportunity in the
              field.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-16 text-gray-600">
            <AiFillLinkedin />
            <AiFillInstagram />
          </div>
          <div></div>
        </section>
      </main>
    </>
  );
}
